// export const GoogleEventSuggestionList = [
//     ".kind"
//   , ".etag"
//   , ".id"
//   , ".status"
//   , ".htmlLink"
//   , ".created"
//   , ".updated"
//   , ".summary"
//   , ".description"
//   , ".location"
//   , ".colorId"
//   , ".creator"
//   , ".creator.id"
//   , ".creator.email"
//   , ".creator.displayName"
//   , ".creator.self"
//   , ".organizer"
//   , ".organizer.id"
//   , ".organizer.email"
//   , ".organizer.displayName"
//   , ".organizer.self"
//   , ".start"
//   , ".start.date"
//   , ".start.dateTime"
//   , ".start.timeZone"
//   , ".end"
//   , ".end.date"
//   , ".end.dateTime"
//   , ".end.timeZone"
//   , ".endTimeUnspecified"
//   , ".recurrence"
//   , ".recurrence[0]"
//   , ".recurringEventId"
//   , ".originalStartTime"
//   , ".originalStartTime.date"
//   , ".originalStartTime.dateTime"
//   , ".originalStartTime.timeZone"
//   , ".transparency"
//   , ".visibility"
//   , ".iCalUID"
//   , ".sequence"
//   , ".attendees"
//   , ".attendees[0]"
//   , ".attendees[0].id"
//   , ".attendees[0].email"
//   , ".attendees[0].displayName"
//   , ".attendees[0].organizer"
//   , ".attendees[0].self"
//   , ".attendees[0].resource"
//   , ".attendees[0].optional"
//   , ".attendees[0].responseStatus"
//   , ".attendees[0].comment"
//   , ".attendees[0].additionalGuests"
//   , ".attendeesOmitted"
//   , ".extendedProperties"
//   , ".extendedProperties.private"
//   , ".extendedProperties.shared"
//   , ".hangoutLink"
//   , ".conferenceData"
//   , ".conferenceData.createRequest"
//   , ".conferenceData.createRequest.requestId"
//   , ".conferenceData.createRequest.conferenceSolutionKey"
//   , ".conferenceData.createRequest.conferenceSolutionKey.type"
//   , ".conferenceData.createRequest.status"
//   , ".conferenceData.createRequest.status.statusCode"
//   , ".conferenceData.entryPoints"
//   , ".conferenceData.entryPoints[0]"
//   , ".conferenceData.entryPoints[0].entryPointType"
//   , ".conferenceData.entryPoints[0].uri"
//   , ".conferenceData.entryPoints[0].label"
//   , ".conferenceData.entryPoints[0].pin"
//   , ".conferenceData.entryPoints[0].accessCode"
//   , ".conferenceData.entryPoints[0].meetingCode"
//   , ".conferenceData.entryPoints[0].passcode"
//   , ".conferenceData.entryPoints[0].password"
//   , ".conferenceData.conferenceSolution"
//   , ".conferenceData.conferenceSolution.key"
//   , ".conferenceData.conferenceSolution.key.type"
//   , ".conferenceData.conferenceSolution.name"
//   , ".conferenceData.conferenceSolution.iconUri"
//   , ".conferenceData.conferenceId"
//   , ".conferenceData.signature"
//   , ".conferenceData.notes"
//   , ".gadget"
//   , ".gadget.type"
//   , ".gadget.title"
//   , ".gadget.link"
//   , ".gadget.iconLink"
//   , ".gadget.width"
//   , ".gadget.height"
//   , ".gadget.display"
//   , ".gadget.preferences"
//   , ".anyoneCanAddSelf"
//   , ".guestsCanInviteOthers"
//   , ".guestsCanModify"
//   , ".guestsCanSeeOtherGuests"
//   , ".privateCopy"
//   , ".locked"
//   , ".reminders"
//   , ".reminders.useDefault"
//   , ".reminders.overrides"
//   , ".reminders.overrides[0]"  
//   , ".reminders.overrides[0].method"
//   , ".reminders.overrides[0].minutes"
//   , ".source"
//   , ".source.url"
//   , ".source.title"
//   , ".attachments"
//   , ".attachments[0]"
//   , ".attachments[0]fileUrl"
//   , ".attachments[0]title"
//   , ".attachments[0]mimeType"
//   , ".attachments[0]iconLink"
//   , ".attachments[0]fileId"
//   , ".eventType"
//   ]



export const GoogleEventSuggestionList = [
    ".anyoneCanAddSelf"
  , ".attachments"
  , ".attachments[0]"
  , ".attachments[0]fileId"
  , ".attachments[0]fileUrl"
  , ".attachments[0]iconLink"
  , ".attachments[0]mimeType"
  , ".attachments[0]title"
  , ".attendees"
  , ".attendeesOmitted"
  , ".attendees[0]"
  , ".attendees[0].additionalGuests"
  , ".attendees[0].comment"
  , ".attendees[0].displayName"
  , ".attendees[0].email"
  , ".attendees[0].id"
  , ".attendees[0].optional"
  , ".attendees[0].organizer"
  , ".attendees[0].resource"
  , ".attendees[0].responseStatus"
  , ".attendees[0].self"
  , ".colorId"
  , ".conferenceData"
  , ".conferenceData.conferenceId"
  , ".conferenceData.conferenceSolution"
  , ".conferenceData.conferenceSolution.iconUri"
  , ".conferenceData.conferenceSolution.key"
  , ".conferenceData.conferenceSolution.key.type"
  , ".conferenceData.conferenceSolution.name"
  , ".conferenceData.createRequest"
  , ".conferenceData.createRequest.conferenceSolutionKey"
  , ".conferenceData.createRequest.conferenceSolutionKey.type"
  , ".conferenceData.createRequest.requestId"
  , ".conferenceData.createRequest.status"
  , ".conferenceData.createRequest.status.statusCode"
  , ".conferenceData.entryPoints"
  , ".conferenceData.entryPoints[0]"
  , ".conferenceData.entryPoints[0].accessCode"
  , ".conferenceData.entryPoints[0].entryPointType"
  , ".conferenceData.entryPoints[0].label"
  , ".conferenceData.entryPoints[0].meetingCode"
  , ".conferenceData.entryPoints[0].passcode"
  , ".conferenceData.entryPoints[0].password"
  , ".conferenceData.entryPoints[0].pin"
  , ".conferenceData.entryPoints[0].uri"
  , ".conferenceData.notes"
  , ".conferenceData.signature"
  , ".created"
  , ".creator"
  , ".creator.displayName"
  , ".creator.email"
  , ".creator.id"
  , ".creator.self"
  , ".description"
  , ".end"
  , ".end.date"
  , ".end.dateTime"
  , ".end.timeZone"
  , ".endTimeUnspecified"
  , ".etag"
  , ".eventType"
  , ".extendedProperties"
  , ".extendedProperties.private"
  , ".extendedProperties.shared"
  , ".gadget"
  , ".gadget.display"
  , ".gadget.height"
  , ".gadget.iconLink"
  , ".gadget.link"
  , ".gadget.preferences"
  , ".gadget.title"
  , ".gadget.type"
  , ".gadget.width"
  , ".guestsCanInviteOthers"
  , ".guestsCanModify"
  , ".guestsCanSeeOtherGuests"
  , ".hangoutLink"
  , ".htmlLink"
  , ".iCalUID"
  , ".id"
  , ".kind"
  , ".location"
  , ".locked"
  , ".organizer"
  , ".organizer.displayName"
  , ".organizer.email"
  , ".organizer.id"
  , ".organizer.self"
  , ".originalStartTime"
  , ".originalStartTime.date"
  , ".originalStartTime.dateTime"
  , ".originalStartTime.timeZone"
  , ".privateCopy"
  , ".parent"
  , ".parent.kind"
  , ".parent.id"
  , ".parent.summary"
  , ".parent.description"
  , ".parent.location"
  , ".parent.timeZone"
  , ".parent.conferenceProperties"
  , ".parent.conferenceProperties.allowedConferenceSolutionTypes"
  , ".recurrence"
  , ".recurrence[0]"
  , ".recurringEventId"
  , ".reminders"
  , ".reminders.overrides"
  , ".reminders.overrides[0]"
  , ".reminders.overrides[0].method"
  , ".reminders.overrides[0].minutes"
  , ".reminders.useDefault"
  , ".sequence"
  , ".source"
  , ".source.title"
  , ".source.url"
  , ".start"
  , ".start.date"
  , ".start.dateTime"
  , ".start.timeZone"
  , ".status"
  , ".summary"
  , ".transparency"
  , ".updated"
  , ".visibility"
]